from django.conf import settings

STARTTIMESTAMP = getattr(settings, 'UIDGENERATOR_START_TIMESTAMP', 1514736000000) #2018-1-1 0:0:0
REGIONIDBITS = getattr(settings, 'UIDGENERATOR_REGIONIDBITS', 3)
WORKERIDBITS = getattr(settings, 'UIDGENERATOR_WORKERIDBITS', 10)
SEQUENCEBITS = getattr(settings, 'UIDGENERATOR_SEQUENCEBITS', 10)

REGIONID = getattr(settings, 'UIDGENERATOR_REGIONID', 1)
WORKERID = getattr(settings, 'UIDGENERATOR_WORKERID', 1)